// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAovkUbHFsT6ResJO660iVH5E5cnBkefQ4',
    appId: '1:270085687016:web:964dbcc84a2ff142c6eb5d',
    messagingSenderId: '270085687016',
    projectId: 'duseca-6e281',
    authDomain: 'duseca-6e281.firebaseapp.com',
    storageBucket: 'duseca-6e281.appspot.com',
    measurementId: 'G-ZT8BB7DFBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC290eHILClxNgyfx_3NI82EAfemMrQGg',
    appId: '1:270085687016:android:df5de001053ae99fc6eb5d',
    messagingSenderId: '270085687016',
    projectId: 'duseca-6e281',
    storageBucket: 'duseca-6e281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-tXDZVMtOAKGdOHy4tjZ4HTQBDXMDseA',
    appId: '1:270085687016:ios:96403503b9f3eb6ec6eb5d',
    messagingSenderId: '270085687016',
    projectId: 'duseca-6e281',
    storageBucket: 'duseca-6e281.appspot.com',
    iosBundleId: 'com.example.dusecasoftware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-tXDZVMtOAKGdOHy4tjZ4HTQBDXMDseA',
    appId: '1:270085687016:ios:96403503b9f3eb6ec6eb5d',
    messagingSenderId: '270085687016',
    projectId: 'duseca-6e281',
    storageBucket: 'duseca-6e281.appspot.com',
    iosBundleId: 'com.example.dusecasoftware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAovkUbHFsT6ResJO660iVH5E5cnBkefQ4',
    appId: '1:270085687016:web:dc48d9143b18b0f7c6eb5d',
    messagingSenderId: '270085687016',
    projectId: 'duseca-6e281',
    authDomain: 'duseca-6e281.firebaseapp.com',
    storageBucket: 'duseca-6e281.appspot.com',
    measurementId: 'G-ZQJ14MJHBK',
  );
}
